# Generated by Django 2.2.13 on 2020-10-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0026_auto_20201013_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='protocol',
            field=models.CharField(choices=[('ssh', 'ssh'), ('rdp', 'rdp'), ('vnc', 'vnc'), ('telnet', 'telnet'), ('mysql', 'mysql'), ('oracle', 'oracle'), ('mariadb', 'mariadb'), ('postgresql', 'postgresql'), ('k8s', 'kubernetes')], db_index=True, default='ssh', max_length=16),
        ),
    ]
