# Generated by Django 2.2.13 on 2020-10-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_k8sapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseapp',
            name='type',
            field=models.CharField(choices=[('mysql', 'MySQL'), ('oracle', 'Oracle'), ('mariadb', 'MariaDB'), ('postgresql', 'PostgreSQL')], default='mysql', max_length=128, verbose_name='Type'),
        ),
    ]
